{
 "title": "Fakemetrics - discarded samples",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "graphite" },
   { "name": "environment", "query": "metrictank.stats.*" },
   {
    "name": "instance",
    "query": "metrictank.stats.$environment.*"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "Use `fakemetrics bad` to generate invalid data points."
  },
  {
   "title": "Metrictank - discarded samples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(metrictank.stats.$environment.$instance.tank.metrics_too_old.counter32, 4, 5)"
    },
    {
     "target": "aliasByNode(metrictank.stats.$environment.$instance.tank.add_to_closed_chunk.counter32, 4, 5)"
    },
    {
     "target": "aliasByNode(metrictank.stats.$environment.$instance.input.*.metricdata.invalid.counter32, 4, 5, 6, 7)"
    },
    {
     "target": "aliasByNode(metrictank.stats.$environment.$instance.input.*.metricpoint.invalid.counter32, 4, 5, 6, 7)"
    },
    {
     "target": "aliasByNode(metrictank.stats.$environment.$instance.input.*.metricpoint.unknown.counter32, 4, 5, 6, 7)"
    }
   ]
  },
  {
   "title": "Prometheus - metrictank_discarded_samples_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (metrictank_discarded_samples_total)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "some.id.of.a.metric.*" }
   ]
  }
 ]
}