{
 "title": "MT-Gateway",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "graphite" },
   { "name": "env", "query": "mt-gateway.stats.*" },
   { "name": "host", "query": "mt-gateway.stats.$env.*" },
   {
    "name": "path",
    "query": "mt-gateway.stats.$env.$host.api.request.*"
   }
  ]
 },
 "panels": [
  {
   "title": "metrics published",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(mt-gateway.stats.$env.$host.output.kafka.published.*.counter32), 6, 7)"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "allocation" }
   ],
   "targets": [
    {
     "target": "groupByNode(mt-gateway.stats.$env.$host.memory.bytes.*.gauge64, 6, 'avg')"
    },
    {
     "target": "alias(averageSeries(mt-gateway.stats.$env.$host.memory.gc.cpu_fraction.gauge32), 'GC cpu fraction - promille')"
    },
    {
     "target": "alias(averageSeries(perSecond(mt-gateway.stats.$env.$host.memory.total_bytes_allocated.counter64)), 'alloc rate')"
    }
   ]
  },
  {
   "title": "metric publish duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(mt-gateway.stats.$env.$host.metrics.publish.latency.{mean,max}.gauge32, 3, 7)"
    }
   ]
  },
  {
   "title": "http latency $path",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "repeat": "path",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(consolidateBy(mt-gateway.stats.$env.*.api.request.$path.latency.mean.gauge32, 'average'), 3, 8)"
    },
    {
     "target": "aliasByNode(consolidateBy(mt-gateway.stats.$env.*.api.request.$path.latency.max.gauge32, 'max'), 3, 8)"
    }
   ]
  },
  {
   "title": "response codes $path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "repeat": "path",
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "groupByNode(perSecond(mt-gateway.stats.$env.$host.api.request.$path.status.*.counter32), 8, 'sum')"
    }
   ]
  },
  {
   "title": "response size $path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "repeat": "path",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "groupByNode(mt-gateway.stats.$env.$host.api.request.$path.size.{mean,p90,max}.gauge32, 8, 'sum')"
    }
   ]
  }
 ]
}