// Code generated by "stringer -type=Format"; DO NOT EDIT.

package chunk

import "fmt"

const _Format_name = "FormatStandardGoTszFormatStandardGoTszWithSpan"

var _Format_index = [...]uint8{0, 19, 46}

func (i Format) String() string {
	if i >= Format(len(_Format_index)-1) {
		return fmt.Sprintf("Format(%d)", i)
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
