package mdata

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ArchiveRequest) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "MetricData":
			err = z.MetricData.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "MetricData")
				return
			}
		case "ChunkWriteRequests":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "ChunkWriteRequests")
				return
			}
			if cap(z.ChunkWriteRequests) >= int(zb0002) {
				z.ChunkWriteRequests = (z.ChunkWriteRequests)[:zb0002]
			} else {
				z.ChunkWriteRequests = make([]ChunkWriteRequestWithoutOrg, zb0002)
			}
			for za0001 := range z.ChunkWriteRequests {
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "ChunkWriteRequests", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "ChunkWriteRequests", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "ChunkWriteRequestPayload":
						err = z.ChunkWriteRequests[za0001].ChunkWriteRequestPayload.DecodeMsg(dc)
						if err != nil {
							err = msgp.WrapError(err, "ChunkWriteRequests", za0001, "ChunkWriteRequestPayload")
							return
						}
					case "Archive":
						err = z.ChunkWriteRequests[za0001].Archive.DecodeMsg(dc)
						if err != nil {
							err = msgp.WrapError(err, "ChunkWriteRequests", za0001, "Archive")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "ChunkWriteRequests", za0001)
							return
						}
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ArchiveRequest) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "MetricData"
	err = en.Append(0x82, 0xaa, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = z.MetricData.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "MetricData")
		return
	}
	// write "ChunkWriteRequests"
	err = en.Append(0xb2, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.ChunkWriteRequests)))
	if err != nil {
		err = msgp.WrapError(err, "ChunkWriteRequests")
		return
	}
	for za0001 := range z.ChunkWriteRequests {
		// map header, size 2
		// write "ChunkWriteRequestPayload"
		err = en.Append(0x82, 0xb8, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64)
		if err != nil {
			return
		}
		err = z.ChunkWriteRequests[za0001].ChunkWriteRequestPayload.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "ChunkWriteRequests", za0001, "ChunkWriteRequestPayload")
			return
		}
		// write "Archive"
		err = en.Append(0xa7, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65)
		if err != nil {
			return
		}
		err = z.ChunkWriteRequests[za0001].Archive.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "ChunkWriteRequests", za0001, "Archive")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ArchiveRequest) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "MetricData"
	o = append(o, 0x82, 0xaa, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61)
	o, err = z.MetricData.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "MetricData")
		return
	}
	// string "ChunkWriteRequests"
	o = append(o, 0xb2, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.ChunkWriteRequests)))
	for za0001 := range z.ChunkWriteRequests {
		// map header, size 2
		// string "ChunkWriteRequestPayload"
		o = append(o, 0x82, 0xb8, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64)
		o, err = z.ChunkWriteRequests[za0001].ChunkWriteRequestPayload.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "ChunkWriteRequests", za0001, "ChunkWriteRequestPayload")
			return
		}
		// string "Archive"
		o = append(o, 0xa7, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65)
		o, err = z.ChunkWriteRequests[za0001].Archive.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "ChunkWriteRequests", za0001, "Archive")
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ArchiveRequest) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "MetricData":
			bts, err = z.MetricData.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "MetricData")
				return
			}
		case "ChunkWriteRequests":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ChunkWriteRequests")
				return
			}
			if cap(z.ChunkWriteRequests) >= int(zb0002) {
				z.ChunkWriteRequests = (z.ChunkWriteRequests)[:zb0002]
			} else {
				z.ChunkWriteRequests = make([]ChunkWriteRequestWithoutOrg, zb0002)
			}
			for za0001 := range z.ChunkWriteRequests {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ChunkWriteRequests", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "ChunkWriteRequests", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "ChunkWriteRequestPayload":
						bts, err = z.ChunkWriteRequests[za0001].ChunkWriteRequestPayload.UnmarshalMsg(bts)
						if err != nil {
							err = msgp.WrapError(err, "ChunkWriteRequests", za0001, "ChunkWriteRequestPayload")
							return
						}
					case "Archive":
						bts, err = z.ChunkWriteRequests[za0001].Archive.UnmarshalMsg(bts)
						if err != nil {
							err = msgp.WrapError(err, "ChunkWriteRequests", za0001, "Archive")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "ChunkWriteRequests", za0001)
							return
						}
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ArchiveRequest) Msgsize() (s int) {
	s = 1 + 11 + z.MetricData.Msgsize() + 19 + msgp.ArrayHeaderSize
	for za0001 := range z.ChunkWriteRequests {
		s += 1 + 25 + z.ChunkWriteRequests[za0001].ChunkWriteRequestPayload.Msgsize() + 8 + z.ChunkWriteRequests[za0001].Archive.Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ChunkWriteRequestPayload) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "TTL":
			z.TTL, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "TTL")
				return
			}
		case "T0":
			z.T0, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "T0")
				return
			}
		case "Data":
			z.Data, err = dc.ReadBytes(z.Data)
			if err != nil {
				err = msgp.WrapError(err, "Data")
				return
			}
		case "Timestamp":
			z.Timestamp, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ChunkWriteRequestPayload) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "TTL"
	err = en.Append(0x84, 0xa3, 0x54, 0x54, 0x4c)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.TTL)
	if err != nil {
		err = msgp.WrapError(err, "TTL")
		return
	}
	// write "T0"
	err = en.Append(0xa2, 0x54, 0x30)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.T0)
	if err != nil {
		err = msgp.WrapError(err, "T0")
		return
	}
	// write "Data"
	err = en.Append(0xa4, 0x44, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Data)
	if err != nil {
		err = msgp.WrapError(err, "Data")
		return
	}
	// write "Timestamp"
	err = en.Append(0xa9, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
	if err != nil {
		return
	}
	err = en.WriteTime(z.Timestamp)
	if err != nil {
		err = msgp.WrapError(err, "Timestamp")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ChunkWriteRequestPayload) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "TTL"
	o = append(o, 0x84, 0xa3, 0x54, 0x54, 0x4c)
	o = msgp.AppendUint32(o, z.TTL)
	// string "T0"
	o = append(o, 0xa2, 0x54, 0x30)
	o = msgp.AppendUint32(o, z.T0)
	// string "Data"
	o = append(o, 0xa4, 0x44, 0x61, 0x74, 0x61)
	o = msgp.AppendBytes(o, z.Data)
	// string "Timestamp"
	o = append(o, 0xa9, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
	o = msgp.AppendTime(o, z.Timestamp)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ChunkWriteRequestPayload) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "TTL":
			z.TTL, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TTL")
				return
			}
		case "T0":
			z.T0, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "T0")
				return
			}
		case "Data":
			z.Data, bts, err = msgp.ReadBytesBytes(bts, z.Data)
			if err != nil {
				err = msgp.WrapError(err, "Data")
				return
			}
		case "Timestamp":
			z.Timestamp, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ChunkWriteRequestPayload) Msgsize() (s int) {
	s = 1 + 4 + msgp.Uint32Size + 3 + msgp.Uint32Size + 5 + msgp.BytesPrefixSize + len(z.Data) + 10 + msgp.TimeSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ChunkWriteRequestWithoutOrg) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ChunkWriteRequestPayload":
			err = z.ChunkWriteRequestPayload.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "ChunkWriteRequestPayload")
				return
			}
		case "Archive":
			err = z.Archive.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Archive")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ChunkWriteRequestWithoutOrg) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "ChunkWriteRequestPayload"
	err = en.Append(0x82, 0xb8, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64)
	if err != nil {
		return
	}
	err = z.ChunkWriteRequestPayload.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "ChunkWriteRequestPayload")
		return
	}
	// write "Archive"
	err = en.Append(0xa7, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65)
	if err != nil {
		return
	}
	err = z.Archive.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Archive")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ChunkWriteRequestWithoutOrg) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "ChunkWriteRequestPayload"
	o = append(o, 0x82, 0xb8, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64)
	o, err = z.ChunkWriteRequestPayload.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "ChunkWriteRequestPayload")
		return
	}
	// string "Archive"
	o = append(o, 0xa7, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65)
	o, err = z.Archive.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Archive")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ChunkWriteRequestWithoutOrg) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ChunkWriteRequestPayload":
			bts, err = z.ChunkWriteRequestPayload.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "ChunkWriteRequestPayload")
				return
			}
		case "Archive":
			bts, err = z.Archive.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Archive")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ChunkWriteRequestWithoutOrg) Msgsize() (s int) {
	s = 1 + 25 + z.ChunkWriteRequestPayload.Msgsize() + 8 + z.Archive.Msgsize()
	return
}
