// Code generated by "stringer -type=Method"; DO NOT EDIT.

package conf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Avg-1]
	_ = x[Sum-2]
	_ = x[Lst-3]
	_ = x[Max-4]
	_ = x[Min-5]
}

const _Method_name = "AvgSumLstMaxMin"

var _Method_index = [...]uint8{0, 3, 6, 9, 12, 15}

func (i Method) String() string {
	i -= 1
	if i < 0 || i >= Method(len(_Method_index)-1) {
		return "Method(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Method_name[_Method_index[i]:_Method_index[i+1]]
}
