// Code generated by "stringer -type=NodeMode -trimprefix=Mode"; DO NOT EDIT.

package cluster

import "strconv"

const _NodeMode_name = "ShardDevQuery"

var _NodeMode_index = [...]uint8{0, 5, 8, 13}

func (i NodeMode) String() string {
	if i >= NodeMode(len(_NodeMode_index)-1) {
		return "NodeMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeMode_name[_NodeMode_index[i]:_NodeMode_index[i+1]]
}
