// Code generated by "stringer -type=NodeState"; DO NOT EDIT

package cluster

import "fmt"

const _NodeState_name = "NodeNotReadyNodeReadyNodeUnreachable"

var _NodeState_index = [...]uint8{0, 12, 21, 36}

func (i NodeState) String() string {
	if i < 0 || i >= NodeState(len(_NodeState_index)-1) {
		return fmt.Sprintf("NodeState(%d)", i)
	}
	return _NodeState_name[_NodeState_index[i]:_NodeState_index[i+1]]
}
