// Code generated by "stringer -type=ResultType"; DO NOT EDIT.

package cache

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Miss-0]
	_ = x[HitPartial-1]
	_ = x[Hit-2]
}

const _ResultType_name = "MissHitPartialHit"

var _ResultType_index = [...]uint8{0, 4, 14, 17}

func (i ResultType) String() string {
	if i >= ResultType(len(_ResultType_index)-1) {
		return "ResultType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResultType_name[_ResultType_index[i]:_ResultType_index[i+1]]
}
