// Code generated by "stringer -type=argType"; DO NOT EDIT.

package expr

import "fmt"

const _argType_name = "seriesseriesListseriesListsintegerintegersfloatstrboolean"

var _argType_index = [...]uint8{0, 6, 16, 27, 34, 42, 47, 50, 57}

func (i argType) String() string {
	if i >= argType(len(_argType_index)-1) {
		return fmt.Sprintf("argType(%d)", i)
	}
	return _argType_name[_argType_index[i]:_argType_index[i+1]]
}
