// Code generated by "stringer -type=exprType"; DO NOT EDIT.

package expr

import "fmt"

const _exprType_name = "etNameetBooletFuncetConstetString"

var _exprType_index = [...]uint8{0, 6, 12, 18, 25, 33}

func (i exprType) String() string {
	if i < 0 || i >= exprType(len(_exprType_index)-1) {
		return fmt.Sprintf("exprType(%d)", i)
	}
	return _exprType_name[_exprType_index[i]:_exprType_index[i+1]]
}
